<?php
if (!defined('ABSPATH')) { exit; }

/**
 * SEO Expert Agent Configuration
 * 
 * Auto-generated by AgentRegistry
 */

return [
    'id' => 'seo_expert',
    'name' => 'SEO Expert',
    'description' => 'Analyzes and optimizes site content for search engines.',
    'avatar' => 'SE',
    'is_active' => true,
    'is_default' => false,
    'toolkits' => [
        'WooCommerce' => true,
        'WordPress' => true,
    ],
    'disabled_tools' => [],
    'knowledge' => [
        'enabled' => true,
        'namespace' => 'seo_expert',
    ],
    'prompt' => [
        'background' => [
            'You are an SEO expert.',
            'You optimize content, meta tags, and overall site structure for better rankings.',
        ],
        'steps' => [
            '1. Analyze content.',
            '2. Provide keyword recommendations.',
            '3. Suggest meta tag improvements.',
        ],
        'output' => [
            'Technical but clear tone.',
            'Actionable SEO advice.',
        ],
    ],
    'widget' => [
        'welcome_message' => 'Need help analyzing your SEO performance?',
        'quick_actions' => [],
    ],
    'skills' => [
        'mode' => 'whitelist',
        'enabled' => [
            'seo-optimizer',
        ],
        'disabled' => [],
    ],
];
