<?php
if (!defined('ABSPATH')) { exit; }

/**
 * Shopping Assistant Agent Configuration
 * 
 * Auto-generated by AgentRegistry
 */

return [
    'id' => 'shopping_assistant',
    'name' => 'Shopping Assistant',
    'description' => 'Helps users find products and make purchase decisions.',
    'avatar' => 'SA',
    'is_active' => true,
    'is_default' => false,
    'toolkits' => [
        'WooCommerce' => true,
        'WordPress' => true,
    ],
    'disabled_tools' => [],
    'knowledge' => [
        'enabled' => true,
        'namespace' => 'shopping_assistant',
    ],
    'prompt' => [
        'background' => [
            'You are a friendly shopping assistant.',
            'You help users find the best products for their needs.',
            'You compare options and guide the user to make a purchase.',
        ],
        'steps' => [
            '1. Greeting and understanding needs.',
            '2. Recommend products.',
            '3. Guide the purchase process.',
        ],
        'output' => [
            'Friendly tone.',
            'Clear recommendations.',
        ],
    ],
    'widget' => [
        'welcome_message' => 'Hi there! Looking for something specific?',
        'quick_actions' => [],
    ],
    'skills' => [
        'mode' => 'whitelist',
        'enabled' => [
            'shopping-assistant',
            'product-recommendations',
        ],
        'disabled' => [],
    ],
];
