<?php
if (!defined('ABSPATH')) { exit; }

/**
 * Customer Support Agent Configuration
 * 
 * Professional support agent for general inquiries, tracking, and issue escalation.
 * 
 * Auto-generated by AgentRegistry
 */

return [
    'id' => 'customer_support',
    'name' => 'Customer Support',
    'description' => 'Professional support agent for general inquiries, tracking, and issue escalation.',
    'avatar' => 'AI',
    'is_active' => true,
    'is_default' => true,
    'toolkits' => 
    [
      'WooCommerce' => true,
      'WordPress' => true,
      'FAQ' => true,
    ],
    'disabled_tools' => 
    [
    ],
    'knowledge' => 
    [
      'enabled' => true,
      'namespace' => 'customer_support',
      'sources' => 
      [
        0 => 7,
        1 => 1,
        2 => 5,
        3 => 4,
        4 => 6,
        5 => 3,
        6 => 2,
      ],
    ],
    'mcp_configs' => 
    [
      'tavily' => 
      [
        'enabled' => true,
        'config' => 
        [
        ],
      ],
    ],
    'mcp_widget_security' => 
    [
    ],
    'prompt' => 
    [
      'background' => 
      [
      ],
      'steps' => 
      [
      ],
      'output' => 
      [
      ],
      'tools_usage' => 
      [
      ],
    ],
    'widget' => 
    [
      'welcome_message' => 'Hi! How can I assist you today? I\'m here to help with any questions, orders, or support issues.',
      'quick_actions' => 
      [
      ],
    ],
    'skills' => 
    [
      'mode' => 'whitelist',
      'enabled' => 
      [
        0 => 'order-lookup',
        1 => 'refund-handling',
        2 => 'faq-responder',
        3 => 'form-builder',
      ],
      'disabled' => 
      [
      ],
    ],
    'documents' => 
    [
      'enabled_sections' => 
      [
      ],
    ],
];
