<?php
if (!defined('ABSPATH')) { exit; }

/**
 * Content Creator Agent Configuration
 * 
 * Writes blog posts, product descriptions, and marketing copy.
 * 
 * Auto-generated by AgentRegistry
 */

return [
    'id' => 'content_creator',
    'name' => 'Content Creator',
    'description' => 'Writes blog posts, product descriptions, and marketing copy.',
    'avatar' => 'CC',
    'is_active' => true,
    'is_default' => false,
    'toolkits' => 
    [
      'WooCommerce' => true,
      'WordPress' => true,
    ],
    'disabled_tools' => 
    [
    ],
    'knowledge' => 
    [
      'enabled' => true,
      'namespace' => 'content_creator',
      'sources' => 
      [
      ],
    ],
    'mcp_configs' => 
    [
    ],
    'mcp_widget_security' => 
    [
    ],
    'prompt' => 
    [
      'background' => 
      [
        0 => 'You are a creative content creator.',
        1 => 'You write compelling product descriptions, blog posts, and marketing materials.',
      ],
      'steps' => 
      [
        0 => '1. Understand the topic or product.',
        1 => '2. Draft the content.',
        2 => '3. Review for tone and quality.',
      ],
      'output' => 
      [
        0 => 'Creative and engaging tone.',
        1 => 'Well-structured formatting.',
      ],
      'tools_usage' => 
      [
      ],
    ],
    'widget' => 
    [
      'welcome_message' => 'Need help writing some amazing content?',
      'quick_actions' => 
      [
      ],
    ],
    'skills' => 
    [
      'mode' => 'whitelist',
      'enabled' => 
      [
        0 => 'content-creator',
        1 => 'auto-blogger',
        2 => 'product-description-writer',
      ],
      'disabled' => 
      [
      ],
    ],
    'documents' => 
    [
      'enabled_sections' => 
      [
      ],
    ],
];
