<?php
if (!defined('ABSPATH')) { exit; }

/**
 * Support Bot Agent Configuration
 * 
 * A dedicated support assistant that answers frequently asked questions, troubleshoots common issues, and guides customers to the right resources.
 * 
 * Auto-generated by AgentRegistry
 */

return [
    'id' => 'free_support_bot',
    'name' => 'Support Bot',
    'description' => 'A dedicated support assistant that answers frequently asked questions, troubleshoots common issues, and guides customers to the right resources.',
    'avatar' => 'SB',
    'is_active' => true,
    'is_default' => false,
    'toolkits' => 
    [
    ],
    'disabled_tools' => 
    [
    ],
    'knowledge' => 
    [
      'enabled' => true,
      'namespace' => 'free_support_bot',
      'sources' => 
      [
        0 => 2,
        1 => 1,
      ],
    ],
    'mcp_configs' => 
    [
    ],
    'mcp_widget_security' => 
    [
    ],
    'prompt' => 
    [
      'background' => 
      [
        0 => 'You are a professional and empathetic Support Bot.',
        1 => 'Your mission is to help customers resolve their questions and issues as quickly as possible.',
        2 => 'You rely on your training knowledge and any knowledge-base documents to provide accurate answers.',
        3 => 'If you cannot resolve an issue, guide the customer to contact human support.',
      ],
      'steps' => 
      [
        0 => '1. Acknowledge the customer\'s question or concern with empathy.',
        1 => '2. Identify the core issue or question from their message.',
        2 => '3. Provide a clear, step-by-step answer or solution using your knowledge base.',
        3 => '4. If the issue is beyond your capabilities, honestly say so and recommend they reach out to human support.',
        4 => '5. Ask if there is anything else you can help with after resolving the question.',
      ],
      'output' => 
      [
        0 => 'Be empathetic and professional at all times.',
        1 => 'Keep responses concise — aim for 2-3 sentences per reply unless a detailed walkthrough is needed.',
        2 => 'Never guess or fabricate answers. Accuracy builds trust.',
        3 => 'Use numbered steps when explaining multi-step processes.',
      ],
      'tools_usage' => 
      [
      ],
    ],
    'widget' => 
    [
      'welcome_message' => 'Hi there! I\'m your Support Bot. How can I help you today?',
      'quick_actions' => 
      [
        0 => 
        [
          'label' => '',
          'action' => '',
          'params' => 
          [
          ],
        ],
        1 => 
        [
          'label' => '',
          'action' => '',
          'params' => 
          [
          ],
        ],
        2 => 
        [
          'label' => '',
          'action' => '',
          'params' => 
          [
          ],
        ],
      ],
    ],
    'skills' => 
    [
      'mode' => 'whitelist',
      'enabled' => 
      [
      ],
      'disabled' => 
      [
      ],
    ],
    'documents' => 
    [
      'enabled_sections' => 
      [
      ],
    ],
];
