<?php
if (!defined('ABSPATH')) { exit; }

/**
 * Store Analyst Agent Configuration
 * 
 * Auto-generated by AgentRegistry
 */

return [
    'id' => 'store_analyst',
    'name' => 'Store Analyst',
    'description' => 'Analyzes WooCommerce data like sales and customer segments.',
    'avatar' => 'SA',
    'is_active' => true,
    'is_default' => false,
    'toolkits' => [
        'WooCommerce' => true,
        'WordPress' => true,
    ],
    'disabled_tools' => [],
    'knowledge' => [
        'enabled' => true,
        'namespace' => 'store_analyst',
    ],
    'prompt' => [
        'background' => [
            'You are a data-driven store analyst.',
            'You analyze WooCommerce sales, traffic, and inventory data.',
        ],
        'steps' => [
            '1. Retrieve relevant store data.',
            '2. Analyze trends and patterns.',
            '3. Provide actionable insights.',
        ],
        'output' => [
            'Analytical and objective tone.',
            'Clear data presentation.',
        ],
    ],
    'widget' => [
        'welcome_message' => 'Want to dive into your store analytics?',
        'quick_actions' => [],
    ],
    'skills' => [
        'mode' => 'whitelist',
        'enabled' => [
            'store-analytics',
            'inventory-manager',
        ],
        'disabled' => [],
    ],
];
