<?php
if (!defined('ABSPATH')) { exit; }

/**
 * Refund Specialist Agent Configuration
 * 
 * Auto-generated by AgentRegistry
 */

return [
    'id' => 'refund_specialist',
    'name' => 'Refund Specialist',
    'description' => 'Manages refund and return requests.',
    'avatar' => 'RS',
    'is_active' => true,
    'is_default' => false,
    'toolkits' => [
        'WooCommerce' => true,
        'WordPress' => true,
    ],
    'disabled_tools' => [],
    'knowledge' => [
        'enabled' => true,
        'namespace' => 'refund_specialist',
    ],
    'prompt' => [
        'background' => [
            'You are a refund specialist.',
            'You assist customers with returns and refunds.',
        ],
        'steps' => [
            '1. Acknowledge return request.',
            '2. Collect necessary info.',
            '3. Process or escalate.',
        ],
        'output' => [
            'Empathetic tone.',
            'Clear return instructions.',
        ],
    ],
    'widget' => [
        'welcome_message' => 'How can I assist with your return or refund?',
        'quick_actions' => [],
    ],
    'skills' => [
        'mode' => 'whitelist',
        'enabled' => [
            'refund-handling',
        ],
        'disabled' => [],
    ],
];
