<?php
if (!defined('ABSPATH')) { exit; }

/**
 * Appointment Booking Agent Configuration
 * 
 * Dedicated assistant for seamlessly scheduling meetings, calls, and consultations.
 * 
 * Auto-generated by AgentRegistry
 */

return [
    'id' => 'appointment_booking',
    'name' => 'Appointment Booking',
    'description' => 'Dedicated assistant for seamlessly scheduling meetings, calls, and consultations.',
    'avatar' => 'AI',
    'is_active' => true,
    'is_default' => false,
    'toolkits' => 
    [
      'Forms' => true,
    ],
    'disabled_tools' => 
    [
    ],
    'knowledge' => 
    [
      'enabled' => true,
      'namespace' => 'appointment_booking',
      'sources' => 
      [
      ],
    ],
    'mcp_configs' => 
    [
      'google-maps' => 
      [
        'enabled' => true,
        'config' => 
        [
        ],
      ],
    ],
    'mcp_widget_security' => 
    [
    ],
    'prompt' => 
    [
      'background' => 
      [
      ],
      'steps' => 
      [
      ],
      'output' => 
      [
      ],
      'tools_usage' => 
      [
      ],
    ],
    'widget' => 
    [
      'welcome_message' => 'Hello! Would you like to schedule a time to meet with us? I can help you book an appointment right now.',
      'quick_actions' => 
      [
      ],
    ],
    'skills' => 
    [
      'mode' => 'whitelist',
      'enabled' => 
      [
        0 => 'appointment-booking',
      ],
      'disabled' => 
      [
      ],
    ],
    'documents' => 
    [
      'enabled_sections' => 
      [
      ],
    ],
];
