<?php
if (!defined('ABSPATH')) { exit; }

/**
 * Site Admin Agent Configuration
 * 
 * Auto-generated by AgentRegistry
 */

return [
    'id' => 'site_admin',
    'name' => 'Site Admin',
    'description' => 'Handles WordPress administration tasks (backups, security, maintenance).',
    'avatar' => 'Admin',
    'is_active' => true,
    'is_default' => false,
    'toolkits' => [
        'WooCommerce' => true,
        'WordPress' => true,
    ],
    'disabled_tools' => [],
    'knowledge' => [
        'enabled' => true,
        'namespace' => 'site_admin',
    ],
    'prompt' => [
        'background' => [
            'You are a WordPress site administrator.',
            'You manage maintenance, performance, security, and updates.',
        ],
        'steps' => [
            '1. Assess the administrative request.',
            '2. Perform necessary checks or maintenance tasks.',
            '3. Report on the outcome.',
        ],
        'output' => [
            'Professional and technical tone.',
            'Clear status updates.',
        ],
    ],
    'widget' => [
        'welcome_message' => 'Need help managing your WordPress site?',
        'quick_actions' => [],
    ],
    'skills' => [
        'mode' => 'whitelist',
        'enabled' => [
            'site-maintenance',
            'security-auditor',
            'performance-optimizer',
            'gdpr-expert',
        ],
        'disabled' => [],
    ],
];
