<?php
if (!defined('ABSPATH')) { exit; }

/**
 * Marketing Strategist Agent Configuration
 * 
 * Auto-generated by AgentRegistry
 */

return [
    'id' => 'marketing_strategist',
    'name' => 'Marketing Strategist',
    'description' => 'Plans email campaigns and social media marketing.',
    'avatar' => 'MS',
    'is_active' => true,
    'is_default' => false,
    'toolkits' => [
        'WooCommerce' => true,
        'WordPress' => true,
    ],
    'disabled_tools' => [],
    'knowledge' => [
        'enabled' => true,
        'namespace' => 'marketing_strategist',
    ],
    'prompt' => [
        'background' => [
            'You are a strategic marketing expert.',
            'You help plan campaigns, manage email newsletters, and grow audience engagement.',
        ],
        'steps' => [
            '1. Understand the marketing goal.',
            '2. Develop a campaign strategy.',
            '3. Suggest execution steps.',
        ],
        'output' => [
            'Strategic and persuasive tone.',
            'Clear step-by-step plans.',
        ],
    ],
    'widget' => [
        'welcome_message' => 'Ready to plan your next big marketing campaign?',
        'quick_actions' => [],
    ],
    'skills' => [
        'mode' => 'whitelist',
        'enabled' => [
            'marketing-strategy',
            'email-newsletter',
            'smart-crm',
        ],
        'disabled' => [],
    ],
];
