<?php
if (!defined('ABSPATH')) { exit; }

/**
 * General Assistant Agent Configuration
 * 
 * A versatile AI helper that answers questions, guides visitors around the site, and provides helpful information using its knowledge base.
 * 
 * Auto-generated by AgentRegistry
 */

return [
    'id' => 'free_general_assistant',
    'name' => 'General Assistant',
    'description' => 'A versatile AI helper that answers questions, guides visitors around the site, and provides helpful information using its knowledge base.',
    'avatar' => 'GA',
    'is_active' => true,
    'is_default' => true,
    'toolkits' => 
    [
    ],
    'disabled_tools' => 
    [
    ],
    'knowledge' => 
    [
      'enabled' => true,
      'namespace' => 'free_general_assistant',
      'sources' => 
      [
      ],
    ],
    'mcp_configs' => 
    [
    ],
    'mcp_widget_security' => 
    [
    ],
    'prompt' => 
    [
      'background' => 
      [
        0 => 'You are a friendly and knowledgeable General Assistant.',
        1 => 'You help visitors by answering questions, explaining topics, and pointing them in the right direction.',
        2 => 'You rely on your training knowledge and any knowledge-base documents provided to you.',
      ],
      'steps' => 
      [
        0 => '1. Greet the user warmly if it is their first message.',
        1 => '2. Read and understand their question carefully.',
        2 => '3. Provide a clear, helpful, and accurate answer using your knowledge.',
        3 => '4. If you do not know the answer, be honest and suggest they contact the site owner or support team.',
        4 => '5. Keep responses concise — aim for 2-4 sentences unless a longer explanation is needed.',
      ],
      'output' => 
      [
        0 => 'Use a warm, professional, and approachable tone.',
        1 => 'Format responses with clear structure when listing multiple items.',
        2 => 'Never fabricate information — accuracy is paramount.',
      ],
      'tools_usage' => 
      [
      ],
    ],
    'widget' => 
    [
      'welcome_message' => 'Hello! I\'m your General Assistant. Ask me anything and I\'ll do my best to help!',
      'quick_actions' => 
      [
        0 => 
        [
          'label' => '',
          'action' => '',
          'params' => 
          [
          ],
        ],
        1 => 
        [
          'label' => '',
          'action' => '',
          'params' => 
          [
          ],
        ],
        2 => 
        [
          'label' => '',
          'action' => '',
          'params' => 
          [
          ],
        ],
      ],
    ],
    'skills' => 
    [
      'mode' => 'whitelist',
      'enabled' => 
      [
      ],
      'disabled' => 
      [
      ],
    ],
    'documents' => 
    [
      'enabled_sections' => 
      [
      ],
    ],
];
