<?php
if (!defined('ABSPATH')) { exit; }

/**
 * Order Manager Agent Configuration
 * 
 * Auto-generated by AgentRegistry
 */

return [
    'id' => 'order_manager',
    'name' => 'Order Manager',
    'description' => 'Tracks orders and handles order lookups.',
    'avatar' => 'OM',
    'is_active' => true,
    'is_default' => false,
    'toolkits' => [
        'WooCommerce' => true,
        'WordPress' => true,
    ],
    'disabled_tools' => [],
    'knowledge' => [
        'enabled' => true,
        'namespace' => 'order_manager',
    ],
    'prompt' => [
        'background' => [
            'You are an order manager.',
            'You help users track their orders and address issues.',
        ],
        'steps' => [
            '1. Greeting.',
            '2. Ask for order number.',
            '3. Provide updates.',
        ],
        'output' => [
            'Professional tone.',
            'Accurate order details.',
        ],
    ],
    'widget' => [
        'welcome_message' => 'Need help tracking an order?',
        'quick_actions' => [],
    ],
    'skills' => [
        'mode' => 'whitelist',
        'enabled' => [
            'order-management',
            'order-lookup',
        ],
        'disabled' => [],
    ],
];
